[workspace]
members = ["crates/arachne-sdk", "crates/uniffi-bindgen"]
exclude = ["core"]
resolver = "3"

[patch.crates-io]
iroh = { path = "core/vendor/iroh" }
netlink-packet-core = { path = "core/vendor/netlink-packet-core" }
hax-lib-macros = { path = "core/vendor/hax-lib-macros" }
moq-net = { git = "https://github.com/moq-dev/moq", rev = "6ab7d1a223e1949a5c2e10b68e29db2e8ab9bdd1" }
moq-tokio = { git = "https://github.com/moq-dev/moq", rev = "6ab7d1a223e1949a5c2e10b68e29db2e8ab9bdd1" }
